### ISSUE TITLE
clicking on vote number renders error

### ISSUE THREAD

**Issue by martenson** [ialbert/biostar-central#409] opened 2016-08-09 17:22 UTC
clicking on number of votes in the home page results in the following error:

![screenshot 2016-08-09 13 19 16](https://cloud.githubusercontent.com/assets/1814954/17526140/02d97412-5e34-11e6-8029-e542490865b7.png)

It seems to try send a POST request to add my vote, but does not have the proper payload.

Seen on both https://www.biostars.org/ and https://biostar.usegalaxy.org/ while logged in.

**Comment by ialbert** [comment] 2016-08-09 17:46
What a weird bug - and it been there forever and we've never noticed it before...

**Comment by ialbert** [comment] 2016-08-09 19:10
now I remember where this is coming from - we were exploring allowing people to vote from the main page, but that did not seem like a good idea hence was not pursued further and we missed removing the remaining elements of it.

**Comment by jppampin** [comment] 2018-07-09 05:59
The issue is in the **biostar.js** file. The thing is that you are trying to vote something that doesn't have a **post id**. 

```python
// Vote submission.
    $('[data-type=vote]').each(function () {

        $($(this)).click(function () {
            var elem = $(this);
            var post_id = elem.parent().attr('data-post_id');
            var vote_type = elem.attr('data-type')
            ajax_vote(elem, post_id, vote_type);
        });
    });
```

Simply modify the jquery search pattern from 

     $('.vote').each(function () 

to

    $('[data-type=vote]').each(function ()

This will reach the correct elements. 

Regards,
JPP

**Comment by Natay** [comment] 2021-04-16 14:23
This issue has been fixed in the most current version of Biostar, we disabled front page voting.

**Closed by Natay** 2021-04-16 14:23 UTC
