### ISSUE TITLE
Auto-generated link titles do not reflect changes to original post title

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#435] opened 2017-08-09 13:45 UTC
Biostars does this nifty little trick where you don't need to specify link text when you're linking to an internal post - it automatically picks up an optional prefix (`A:` or `C:`) and appends the title of the post to this prefix to generate the link text.

However, it would seem that the dataset used to generate this text might be cached, and only updated on new posts - not on post edits. What this means is that the title used in link text autogeneration is from when the referred post was created, not the current title of the referred post.

See, for example, my comment here: https://www.biostars.org/p/266795/#266887

"How do I ask a question on Biostars" was the original title of [this post](https://www.biostars.org/p/179963/). Once I started adding to that post though, I changed the title to reflect the contents better. However, when I link to that post now, the old name is used, not the current name.

Does this warrant fixing?

**Comment by ialbert** [comment] 2017-08-22 13:59
Yes, the answers/comments also have a title (that is not displayed normally) that is inherited from the main post at the time that the answer is created but it does not update after that. We could make it do so, though there are some issues once the thread is large it could have hundreds of contributions. 

Or alternatively, it could display the main thread title. But then that would require another look up during rendering and would affect performance. 

The problem is valid and it is more about prioritizing it relative to other issues.

**Comment by Natay** [comment] 2021-04-16 14:07
This issue has been fixed in the most current version of biostars

**Closed by Natay** 2021-04-16 14:07 UTC
