### ISSUE TITLE
Error when installing 3.0

### ISSUE THREAD

**Issue by Sshuichi** [ialbert/biostar-central#341] opened 2015-04-17 21:02 UTC
*** Indexing site content
Removing all documents from your index because you said so.
All documents removed.
Indexing 104 posts
ERROR:root:Error updating forum using default 
Traceback (most recent call last):
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 191, in update
    doc = index.full_prepare(obj)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/indexes.py", line 207, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/sshuichi/biostar-central/biostar3/forum/search_indexes.py", line 31, in prepare
    data['domain'] = obj.root.usergroup.domain
AttributeError: 'NoneType' object has no attribute 'domain'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/rebuild_index.py", line 16, in handle
    call_command('update_index', **options)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 184, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 189, in handle_label
    self.update_backend(label, using)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 234, in update_backend
    do_update(backend, index, qs, start, end, total, self.verbosity)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/management/commands/update_index.py", line 89, in do_update
    backend.update(index, current_qs)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 191, in update
    doc = index.full_prepare(obj)
  File "/home/sshuichi/.virtualenvs/biostars/local/lib/python2.7/site-packages/haystack/indexes.py", line 207, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/sshuichi/biostar-central/biostar3/forum/search_indexes.py", line 31, in prepare
    data['domain'] = obj.root.usergroup.domain
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by ialbert** [comment] 2015-04-17 22:03
thanks for reporting, will fix it.

**Comment by Sshuichi** [comment] 2015-04-17 22:04
Thanks for your prompt answers !

**Comment by ialbert** [comment] 2015-04-17 22:07
don;t close it until fixed ;-)

**Comment by ialbert** [comment] 2015-04-21 15:20
Can you please indicate the commands you ran that lead to the error. I cannot reproduce it with a fresh install. It might have to do with the order data was created - signals should populate the group for each post.

    ./biostar.sh delete init index

**Comment by Sshuichi** [comment] 2015-04-21 15:21
Hi ! 
I will rerun the installation this night, please wait until I get home.

**Comment by Sshuichi** [comment] 2015-04-22 21:25
Ok, the error occured / still occuring when running this command
`./biostar.sh delete import init index run`

The command you stated works fine. `run` works fine as well. so the problem should be with the import function.

If you need anything else let me know

**Comment by llaisdy** [comment] 2015-04-23 16:02
Dear Istvan

For me, just now, it's the index step that causes the error, so:
$ ./biostar.sh delete import init    # ok
$ ./biostar.sh index    # error as above
$ $ ./biostar.sh run    # site runs:

- main body shows no posts
- "Recent Votes" sidebar shows post links
- post links get errors, e.g.:

    AttributeError at /p/69/
    'NoneType' object has no attribute 'public'

Thanks

Ivan

**Comment by llaisdy** [comment] 2015-04-23 16:09
Seems impossible to sign in however (inc. with 1@localhost.com).

**Comment by ialbert** [comment] 2015-04-23 16:57
sorry about that now I realize the docs are incomplete of order the correct chain of action is:

    ./biostar.sh delete migrate index run


this is because currently the site will ensure that the migration from 2 to 3 is seamless so it loads up data from biostar 2 and transforms it into data for biostar3

The docs will refer to what to do when starting with a brand new site but the current imported data is still for 2.0.

You should be able to now log in using 1@localhost.com as username and password.

**Comment by ialbert** [comment] 2015-04-23 17:07
I want to make a note that as the readme says run your localhost as http://www.lvh.me:8080/ (this resolves to localhost as well) to allow the site to extract the groups from subdomain data.

**Closed by ialbert** 2015-04-23 17:07 UTC

**Comment by llaisdy** [comment] 2015-04-27 07:46
Thanks v much! All working now :)

**Comment by ialbert** [comment] 2015-04-28 13:54
Hey one question to you guys early adopters and testers.

how would you feel about if Biostar were Python 3 only? Would that be a big disruption to you, would you prefer that etc?

**Comment by tvvocold** [comment] 2015-04-28 14:13
`Short version: Python 2.x is legacy, Python 3.x is the present and future of the language`
Source: https://wiki.python.org/moin/Python2orPython3

Since it is Biostar v3, so why not Python 3? :)

**Comment by ialbert** [comment] 2015-04-28 14:26
@tvvocold - the site does work with Python 3 already the question is whether to move to Python 3 only. As long as it has to support both versions the code is more complicated and one cannot actually make use of any Python 3 functionality.

**Comment by tvvocold** [comment] 2015-04-28 14:31
@ialbert 
I think my point is P3 only.

**Comment by llaisdy** [comment] 2015-04-29 08:58
I don't use Python very much these days.  It would certainly simplify things a lot for me if people stopped using 2.x and "Python" just meant python 3.x.

I'd be happy if Biostars3 were python 3 only.  I don't think it would cause any disruption at all.

**Comment by Sshuichi** [comment] 2015-04-30 11:46
Hello,
Python 3 actually solves a lot of pitfalls in Python 2.
I'd say the changes would affect in the developer in the first degree and the least the end user which is in our case, the early adopters.

So yeah go for Python 3 if you feel more confortable with it and thanks for the efforts.
