### ISSUE TITLE
Django 1.8?

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#337] opened 2015-04-13 14:36 UTC
Dear All

I need to make some model changes (e.g., to the User Profile), so I'm looking into migrating models.  It seems Django 1.7 & 1.8 handle migrations natively (instead of using third party tools like South), so I'm thinking about upgrading to Django 1.8 (also I note that Django 1.6 is no longer supported).

Can you think of any parts of biostar that might balk at this?  In the meantime I'll go ahead and I'll report back.

Thanks

Ivan

**Comment by ialbert** [comment] 2015-04-13 14:56
I would be careful with 1.8 it could be trouble since that is two full release cycles ahead - there are actually many internal changes that manifest themselves within the way we use libraries. 

South still works with 1.7 AFIK only the directory needs to be renamed to something else.

**Comment by llaisdy** [comment] 2015-04-13 14:59
Thanks for the warning.  I'll try (carefully) with 1.8 and revert if I hit bad snags.

Ivan

**Comment by llaisdy** [comment] 2015-04-14 07:15
I've had second thoughts :D we have to diverge a little bit, but I should probably diverge as little as possible.  I'll stick with Django 1.6 and follow biostar's plans for upgrade to Django 1.7/8.

Thanks

Ivan

**Comment by brainstorm** [comment] 2015-04-14 07:36
@llaisdy Was that migration attempt so painful? I'm working in another Django 1.6 project and I wanted to know which roadblocks you found in the way.

@merry-bits

**Comment by llaisdy** [comment] 2015-04-14 07:40
I didn't try.  I decided to stick to the version of Django used by biostar.  I see Biostar 3.0 uses Django 1.7 so I might upgrade to that and bypass South.  (Currently setting up a clone of my local dev vm so I can try it all out without wrecking the "working" dev vm).

**Comment by nimiq** [comment] 2015-04-14 08:22
I recently updated a project from Django 1.6 to 1.7.
We didn't need to keep all migration files and so the update was very easy.
The procedure I followed was (more or less):
- remove south from the codebase (requirements and settings.INSTALLED_APPS);
- drop south_* tables from the database;
- in the `migrations` dir in every app: delete every file but `__init__.py`;
- upgrade Django (update the requirements and install Django 1.7.7);
- create initial migrations: `./manage.py makemigrations`;
- fake initial migrations: `manage.py migrate --fake`.

The idea is: migrations are incremental changes to the database that make it match all historical versions of you models. In our case, when upgrading to a new version of Django, we were only interested in keeping the latest version of our models (not all historical versions), so the procedure we followed reset the migrations: this means that only 1 migration per application was created and it matched the current version of the models.

**Comment by ialbert** [comment] 2015-04-14 11:42
I had unexpected difficulties migrating the new code written for 1.7 to 1.8 - I am yet unsure what the source of the problem is  -

I have a sense what causes it - I put in workaround to let the site developed for 1.6 upgrade itself to 1.7 but then once I update again to 1.8 I have problems with the migrations apply cleanly across the entire 1.6 -> 1.7 -> 1.8 sequence. 1. 8 has stricter rules on app naming an load order.

**Comment by ialbert** [comment] 2016-02-27 15:02
We are in issue cleanup mode, we'll close issues that are not strictly software related.

In the meantime we are moving to Django 1.10 (even though not released it will have a feature called channels that allows us to drop the celery backend)

**Closed by ialbert** 2016-02-27 15:02 UTC
