### ISSUE TITLE
biostar + github integration

### ISSUE THREAD

**Issue by satra** [ialbert/biostar-central#389] opened 2015-08-25 16:44 UTC
a request on our neuroimaging mailing list  via @vsoch and @bcipolli 

would it be possible to integrate issues of a repo on github with biostars?

**Comment by ialbert** [comment] 2015-08-26 02:32
I am sure GitHub has an API and that could perform a call bacl into Biostar - it would probably not be all that complicated to set up.

**Comment by vsoch** [comment] 2015-08-26 02:44
Awesome!

**Comment by dneelyep** [comment] 2015-12-10 06:05
Here's the page describing the Github Issues API: https://developer.github.com/v3/issues/.

What functionality is desired for the Biostars site? Should a question be added for every issue in the Github Issues list, automatically tagged/etc? Or something else?

**Comment by satra** [comment] 2015-12-10 13:42
these two sound good:

- one question per github issue
- automatically tagged with repo and github id

it's always going to be hard to map a tree to a list. but here are some thoughts:

- one possibility is to have a custom page for github issues that simply uses github's list format
- sync between the two
- record the info in the search database
- allow a button to post a question as an issue to the github repo (and put a reverse pointer to neurostars).

**Comment by vsoch** [comment] 2015-12-10 18:55
I second a button that:

- is exposed for users that have linked Github accounts, and greyed out if not (with a mouseover to tell them it will be functional if they do link)
- Given authentication with Github asks the user to select a repo. There might be two ways to go about this. 
  - The site could have a list of "pre-registered" Github repos that go along with our core packages, and the user could then just click "post to nilearn" or "post to nibabel."
  - Given that a package has not yet been added to the list, the user should be able to search (or specify) a repo. And possibly the repo gets added to the "remembered" list after that?
- Posting the question pushes the question to the specified repo as an issue, and links to it from the post. The original question should also be in the post itself, for RSS feeds, twitter, etc.

**Comment by yash14123** [comment] 2016-02-09 21:32
Is this issue open? Let me know, would like to fix this.

**Comment by vsoch** [comment] 2016-02-09 21:37
I don't believe anyone has worked on it.

**Comment by yash14123** [comment] 2016-02-10 06:18
Who will be assigning tasks @vsoch ?

**Comment by vsoch** [comment] 2016-02-10 08:13
The right person to ask might be @brainstorm. He deployed the original neurostars.org https://github.com/brainstorm/ansible-neurostars.org

**Comment by brainstorm** [comment] 2016-02-10 12:23
@yash14123 Go ahead if you wish, there's nobody assigning tasks here, just PR away to this repo with your changes ;)

**Comment by alevchuk** [comment] 2016-10-29 22:44
I'd like to give this a shot. Can folks here to advise what is the minimum set of requerments?

We can also maintain a list of we want to have.  Yet we come back to that list after we have the first implementation running in production. That way we can get our early round of feedback from the community.

**Comment by vsoch** [comment] 2016-10-29 23:12
Your timing is good, because I'm working on an app that has Github v3 API integrations as we speak! This seems very reasonable, and I can see a couple of ways of going about it. I'll start with the one that I think is most reasonable, because arguably an issue --> repo should be added by a particular user.

## Setup
 - add biostars as an app. This will give it an id and secret so that users can authenticate with Github via OAuth2 (and maybe this is already set up?). Note that you will need to set whatever permissions are necessary for the functions that are desired (likely write for issues).
 - Once the user is authenticated, this means that we can do requests on the backend using their token, and a single user has 5000 requests per hour, so this should work! At times I've thought about having some primary Github account to do all requests from (and not requiring users to login) but then you run into the rate limit issue.

## Admin Interface
An admin would want to similarity be able to log in, and select a repo (from the set they have access to is a reasonable start, and this includes organizations) and "turn on" a repo for commenting on.  Since I have this open in my terminal now, just check out all the shadoop of information you can get (for up to 30 repos per page) with a single call!

      {'merges_url': 'https://api.github.com/repos/vsoch/bison/merges', 'size': 58, 'default_branch': 'master', 'full_name': 'vsoch/bison', 'name': 'bison', 'compare_url': 'https://api.github.com/repos/vsoch/bison/compare/{base}...{head}', 'forks': 0, 'mirror_url': None, 'has_pages': False, 'milestones_url': 'https://api.github.com/repos/vsoch/bison/milestones{/number}', 'git_refs_url': 'https://api.github.com/repos/vsoch/bison/git/refs{/sha}', 'ssh_url': 'git@github.com:vsoch/bison.git', 'comments_url': 'https://api.github.com/repos/vsoch/bison/comments{/number}', 'branches_url': 'https://api.github.com/repos/vsoch/bison/branches{/branch}', 'issue_events_url': 'https://api.github.com/repos/vsoch/bison/issues/events{/number}', 'open_issues_count': 0, 'archive_url': 'https://api.github.com/repos/vsoch/bison/{archive_format}{/ref}', 'notifications_url': 'https://api.github.com/repos/vsoch/bison/notifications{?since,all,participating}', 'has_wiki': True, 'issues_url': 'https://api.github.com/repos/vsoch/bison/issues{/number}', 'commits_url': 'https://api.github.com/repos/vsoch/bison/commits{/sha}', 'hooks_url': 'https://api.github.com/repos/vsoch/bison/hooks', 'private': False, 'language': 'C', 'stargazers_count': 0, 'deployments_url': 'https://api.github.com/repos/vsoch/bison/deployments', 'has_downloads': True, 'labels_url': 'https://api.github.com/repos/vsoch/bison/labels{/name}', 'id': 66886570, 'pulls_url': 'https://api.github.com/repos/vsoch/bison/pulls{/number}', 'collaborators_url': 'https://api.github.com/repos/vsoch/bison/collaborators{/collaborator}', 'forks_url': 'https://api.github.com/repos/vsoch/bison/forks', 'trees_url': 'https://api.github.com/repos/vsoch/bison/git/trees{/sha}', 'created_at': '2016-08-29T22:54:49Z', 'contributors_url': 'https://api.github.com/repos/vsoch/bison/contributors', 'subscribers_url': 'https://api.github.com/repos/vsoch/bison/subscribers', 'clone_url': 'https://github.com/vsoch/bison.git', 'events_url': 'https://api.github.com/repos/vsoch/bison/events', 'languages_url': 'https://api.github.com/repos/vsoch/bison/languages', 'homepage': None, 'svn_url': 'https://github.com/vsoch/bison', 'subscription_url': 'https://api.github.com/repos/vsoch/bison/subscription', 'git_commits_url': 'https://api.github.com/repos/vsoch/bison/git/commits{/sha}', 'contents_url': 'https://api.github.com/repos/vsoch/bison/contents/{+path}', 'statuses_url': 'https://api.github.com/repos/vsoch/bison/statuses/{sha}', 'git_url': 'git://github.com/vsoch/bison.git', 'watchers_count': 0, 'owner': {'site_admin': False, 'type': 'User', 'following_url': 'https://api.github.com/users/vsoch/following{/other_user}', 'organizations_url': 'https://api.github.com/users/vsoch/orgs', 'starred_url': 'https://api.github.com/users/vsoch/starred{/owner}{/repo}', 'events_url': 'https://api.github.com/users/vsoch/events{/privacy}', 'subscriptions_url': 'https://api.github.com/users/vsoch/subscriptions', 'url': 'https://api.github.com/users/vsoch', 'received_events_url': 'https://api.github.com/users/vsoch/received_events', 'repos_url': 'https://api.github.com/users/vsoch/repos', 'id': 814322, 'avatar_url': 'https://avatars.githubusercontent.com/u/814322?v=3', 'followers_url': 'https://api.github.com/users/vsoch/followers', 'gists_url': 'https://api.github.com/users/vsoch/gists{/gist_id}', 'login': 'vsoch', 'html_url': 'https://github.com/vsoch', 'gravatar_id': ''}, 'blobs_url': 'https://api.github.com/repos/vsoch/bison/git/blobs{/sha}', 'has_issues': True, 'forks_count': 0, 'stargazers_url': 'https://api.github.com/repos/vsoch/bison/stargazers', 'issue_comment_url': 'https://api.github.com/repos/vsoch/bison/issues/comments{/number}', 'pushed_at': '2016-08-30T22:47:18Z', 'permissions': {'push': True, 'pull': True, 'admin': True}, 'updated_at': '2016-08-30T21:58:49Z', 'teams_url': 'https://api.github.com/repos/vsoch/bison/teams', 'keys_url': 'https://api.github.com/repos/vsoch/bison/keys{/key_id}', 'tags_url': 'https://api.github.com/repos/vsoch/bison/tags', 'description': None, 'downloads_url': 'https://api.github.com/repos/vsoch/bison/downloads', 'releases_url': 'https://api.github.com/repos/vsoch/bison/releases{/id}', 'watchers': 0, 'git_tags_url': 'https://api.github.com/repos/vsoch/bison/git/tags{/sha}', 'url': 'https://api.github.com/repos/vsoch/bison', 'html_url': 'https://github.com/vsoch/bison', 'assignees_url': 'https://api.github.com/repos/vsoch/bison/assignees{/user}', 'open_issues': 0, 'fork': False}

The admin adding the repo would save the required necessary info for posting an issue, which I think is just the basic stuffs like user/name. Likely the Github API resolves changed names on the back end and you could just store the name, but I think you would do better to store the repo id and retrieve the (definitely right) user/name from that:

	curl -i -H 'Authorization: token 5199831f4dd3b79e7c5b7e0ebe75d67aa66e79d4' \
	   -d '{ \
		"title": "New logo", \
		"body": "We should have one", \
		"labels": ["design"] \
	      }' \
	   https://api.github.com/repos/pengwynn/api-sandbox/issues

- So adding a repo on the admin side would first just be saving this minimum info to create issues.
- You would also want to set up a webhook so that new issues on Github (and responses to issues) get sent back to update neurostars. This also means that neurostars needs an endpoint to receive and parse that.

## Use Case - Creating Issue
- Now, a user logs in with Github, and they click a button to create an issue
- Biostars has a small record somewhere of legit repos, and let's the user select one. 
- The user writes their issue / message into a form...
- Submitting the form uses the API to create the issue, with the title mapping to the name, and you could add tags and stuffs too, etc. 

## Use Case - Updating Issue
- Again, the user must be logged in / authenticated with Github so the issue is created by him or her. 
- You would need to get the response for the above to get the issue ID, so that any comments / updates to it would update the issue accordingly!
- On the Github side, if an issue is updated it should trigger the webhook and update neurostars.

We do have the problem of users that don't have Github logins not having their responses pushed to Github. I'm not sure how to deal with that, maybe have a fallback option of using something else (an admin account or deploy key?) to update? Or just kick the users off Neurostars... if they don't use Github they shouldn't be allowed to do science :) Just kidding... or maybe not! :P 

I literally have done magic with this in Django in like, less than an hour, so I think you should have fun and it shouldn't be tricky. Thank goodness for the internet, most of these things just work nicely these days! Hope this helps!

**Comment by vsoch** [comment] 2016-10-29 23:13
And get going soon! [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is going fast!! :jack_o_lantern:

**Comment by alevchuk** [comment] 2016-10-31 20:04
Thanks @vsoch !

I'm starting to work on it. Here is my "internal" TODO list https://github.com/alevchuk/biostar-central/wiki/Biostars-github-integration

**Comment by vsoch** [comment] 2016-10-31 20:11
Cool! I love the checkboxes... I want to try that somewhere too :)

Now I really can say Happy Halloween! :ghost:

**Comment by alevchuk** [comment] 2016-11-11 23:25
Ok, I implemented all except one tasks from the minimum set of requirements. 

The last task to get "updates on github to update Biostars" it tricky because
> Only members with owner privileges for an organization or admin privileges for a repository can manage webhooks for an organization. (https://help.github.com/articles/about-webhooks/)

So GitHub pushing changes Biostars us would not be an option.

So to finish this requirement, I'm planning to create a button that would allow individual users to sync changes from GitHub Issues back to Biostars. Once this functionality is out, we can work out polling mechanism to check periodically instead of asking users to click a button.

**Comment by vsoch** [comment] 2016-11-11 23:40
The webhooks will work given an OAuth2 framework where an admin user (having a Github account associated with one or more repos) generates a token (and you wind up saving the token itself, along with a refresh one) and then uses the token to generate the webhook (or do whatever the token scope is defined for). This would mean that for set up of Biostars, one of the admins would just need to make that connection.

**Comment by alevchuktest** [comment] 2016-11-12 21:53
Having re-think this for about a day, I'd like to go ahead with [code review -> deploy -> merge -> get feedback] on the first iteration with the changes that we have so far.

@vsoch,

We should consider the approach that you described yet I think it's to early to go in that direction now. E.g. syncing comments is not supported yet. I feel like we need feedback from the community as they start using this new feature.

If we have many questions that are connected to the same repo, it would make sense to develop the feature to have webhook setup using secondary token that are provided the the repo admins. Would you write-up a plan/wording on how to encourage repo admins to authorize our sites to subscribe to their repos?

@ialbert,

My parental leave ends this Monday, so I'll like to get this out of the door. :)

Would you review the pull request?

Also, before merging to your branch, to ensure that we are bug-free, would you be willing to deploy to http://biostars.org/ from my branch?
It's easy: This weekend, I will write up a 2 step doc on how to (1) setup a GitHub app and (2) configure it in settings/base.py

**Comment by alevchuk** [comment] 2016-11-12 22:03
Having re-think this for about a day, I'd like to go ahead with [code review -> deploy -> merge -> get feedback] on the first iteration with the changes that we have so far.

@vsoch,

We should consider the approach that you described yet I think it's to early to go in that direction now. E.g. syncing comments is not supported yet. I feel like we need feedback from the community as they start using this new feature.

If we have many questions that are connected to the same repo, it would make sense to develop the feature to have webhook setup using secondary token that are provided the the repo admins. Would you write-up a plan/wording on how to encourage repo admins to authorize our sites to subscribe to their repos?

@ialbert,

My parental leave ends this Monday, so I'll like to get this out of the door. :)

Would you review the pull request?

Also, before merging to your branch, to ensure that we are bug-free, would you be willing to deploy to http://biostars.org/ from my branch?
It's easy: This weekend, I will write up a 2 step doc on how to (1) setup a GitHub app and (2) configure it in settings/base.py

**Comment by ialbert** [comment] 2016-11-12 22:48
I will merge this into a separate branch since I would not have time to fully vet it - plus we need to think more in general if this should be a separate app or part of the main distribution.

**Comment by alevchuk** [comment] 2016-11-12 22:54
When can we vet and deploy to get feedback?

**Comment by ialbert** [comment] 2016-11-12 22:59
Just a quick note - we cannot  deploy to the main branch just yet. 

There are several other sites that also use Biostars and ensuring that everything works  the same way for everyone needs more work that right not I could dedicate.

As I said this should be merged into a separate fork/branch that people that need this functionality can use.

The soonest this would be considered to be merged would around the end of January 2017.

**Comment by vsoch** [comment] 2016-11-12 23:25
> We should consider the approach that you described yet I think it's to early to go in that direction now. E.g. syncing comments is not supported yet. I feel like we need feedback from the community as they start using this new feature.
> 

Definitely!

> If we have many questions that are connected to the same repo, it would make sense to develop the feature to have webhook setup using secondary token that are provided the the repo admins. Would you write-up a plan/wording on how to encourage repo admins to authorize our sites to subscribe to their repos?
> 

It would be totally automatic, here is what I would imagine:

- The super admin (whomever sets up the original site) must [register to get an OAuth2 token](https://github.com/settings/applications/new) for the entire application. This hides in some secrets.py file, somewhere, and is read in to the code when appropriate to render the correct views, etc.
- An admin (user that wants to add some software) clicks to register a new organization code base. Registering means asking the user to grant Biostars permission (getting an OAauth2 token) to work with the user's github. (This is the step where the user is redirected, it says "Biostars would like permission to [insert scope here]) and they hopefully accept. I would recommend reading about OAuth2 and tokens, or using a well developed library (python-social-auth is amazing). It's important that you store the token and the refresh, in case it expires, because you can only get the code to generate it once.
- Once BIostars has access to the users's repos, he/she is able to select the software to add. "Adding" means doing whatever is necessary on the Biostars side to make it findable / taggable, but also generating a webhook.
- The webhook, in its simplest form, can ping biostars when a new issue is made, and biostars can automatically create the same issue as content. More ideally, you can have pings for comments on issues, so the two are synced. This also means that you would want biostars comments to be appended to Github, and this is easy to do, again using the [same API](https://developer.github.com/v3/issues/comments/). You just need to extend the scope to be what you would need.

Hope that helps!

**Closed** 2021-04-17 20:53 UTC
